apiVersion: v1
kind: Service
metadata:
  name: online-shopping-service
  labels:
    app: online-shopping
spec:
  type: NodePort
  selector:
    app: online-shopping
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
